// data.js
export const games = [
  {
    id: 1,
    title: "Minecraft",
    steamPrice: "₹1,999",
    epicPrice: "₹1,899",
    steamLink: "https://store.steampowered.com/app/323910/Minecraft/",
    epicLink: "https://store.epicgames.com/en-US/p/minecraft",
    views: 5200,
    likes: 4700,
    reviews: ["Great sandbox game!", "My kids love it!", "Endless creativity!"],
    type: "basic",
    genre: "Sandbox",
    platform: ["PC"]
  },
  {
    id: 2,
    title: "Grand Theft Auto V",
    steamPrice: "₹2,499",
    epicPrice: "₹2,299",
    steamLink: "https://store.steampowered.com/app/271590/Grand_Theft_Auto_V/",
    epicLink: "https://store.epicgames.com/en-US/p/grand-theft-auto-v",
    views: 8900,
    likes: 8400,
    reviews: ["Classic open-world fun.", "Great storyline.", "Online mode is addictive!"],
    type: "trending",
    genre: "Action",
    platform: ["PC", "PS", "Xbox"]
  },
  {
    id: 3,
    title: "Fortnite",
    steamPrice: "Not Available",
    epicPrice: "Free",
    steamLink: null,
    epicLink: "https://store.epicgames.com/en-US/p/fortnite",
    views: 12000,
    likes: 9500,
    reviews: ["Best battle royale ever!", "Always fresh content.", "Cosmetics are cool!"],
    type: "trending",
    genre: "Battle Royale",
    platform: ["PC", "PS", "Xbox", "Switch"]
  },
  {
    id: 4,
    title: "Among Us",
    steamPrice: "₹129",
    epicPrice: "₹99",
    steamLink: "https://store.steampowered.com/app/945360/Among_Us/",
    epicLink: "https://store.epicgames.com/en-US/p/among-us",
    views: 6300,
    likes: 5100,
    reviews: ["Fun with friends.", "Simple but addictive.", "Great party game."],
    type: "suggested",
    genre: "Party",
    platform: ["PC", "Mobile"]
  },
  {
    id: 5,
    title: "Valorant",
    steamPrice: "Not Available",
    epicPrice: "Free",
    steamLink: null,
    epicLink: "https://store.epicgames.com/en-US/p/valorant",
    views: 8700,
    likes: 7900,
    reviews: ["Best FPS since CS:GO.", "Tactical and fun.", "Characters are unique."],
    type: "suggested",
    genre: "Shooter",
    platform: ["PC"]
  },
  {
    id: 6,
    title: "Elden Ring",
    steamPrice: "₹3,999",
    epicPrice: "₹3,899",
    steamLink: "https://store.steampowered.com/app/1245620/ELDEN_RING/",
    epicLink: "https://store.epicgames.com/en-US/p/elden-ring",
    views: 7600,
    likes: 7100,
    reviews: ["Masterpiece from FromSoftware.", "Challenging and rewarding.", "Amazing open world."],
    type: "trending",
    genre: "Action RPG",
    platform: ["PC", "PS", "Xbox"]
  },
  {
    id: 7,
    title: "Hades",
    steamPrice: "₹999",
    epicPrice: "₹949",
    steamLink: "https://store.steampowered.com/app/1145360/Hades/",
    epicLink: "https://store.epicgames.com/en-US/p/hades",
    views: 3300,
    likes: 3100,
    reviews: ["Top-tier roguelike.", "Art and combat are perfect.", "Highly replayable."],
    type: "basic",
    genre: "Roguelike",
    platform: ["PC", "Switch"]
  },
  {
    id: 8,
    title: "Cyberpunk 2077",
    steamPrice: "₹2,999",
    epicPrice: "₹2,799",
    steamLink: "https://store.steampowered.com/app/1091500/Cyberpunk_2077/",
    epicLink: "https://store.epicgames.com/en-US/p/cyberpunk-2077",
    views: 6700,
    likes: 6200,
    reviews: ["Huge improvement since launch.", "Great story.", "Visuals are amazing."],
    type: "trending",
    genre: "RPG",
    platform: ["PC", "PS", "Xbox"]
  },
  {
    id: 9,
    title: "Terraria",
    steamPrice: "₹369",
    epicPrice: "₹349",
    steamLink: "https://store.steampowered.com/app/105600/Terraria/",
    epicLink: "https://store.epicgames.com/en-US/p/terraria",
    views: 2900,
    likes: 2700,
    reviews: ["2D Minecraft basically.", "Tons of content.", "Multiplayer is fun!"],
    type: "basic",
    genre: "Adventure",
    platform: ["PC", "Mobile"]
  },
  {
    id: 10,
    title: "Rocket League",
    steamPrice: "Not Available",
    epicPrice: "Free",
    steamLink: null,
    epicLink: "https://store.epicgames.com/en-US/p/rocket-league",
    views: 4500,
    likes: 4300,
    reviews: ["Soccer with cars!", "Skill-based fun.", "Crossplay works great."],
    type: "suggested",
    genre: "Sports",
    platform: ["PC", "PS", "Xbox", "Switch"]
  },
    {
    id: 11,
    title: "The Witcher 3: Wild Hunt",
    steamPrice: "₹799",
    epicPrice: "₹749",
    steamLink: "https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
    epicLink: "https://store.epicgames.com/en-US/p/the-witcher-3-wild-hunt",
    views: 5200,
    likes: 4900,
    reviews: ["Rich storytelling.", "Beautiful world.", "Great value."],
    type: "basic",
    genre: "RPG",
    platform: ["PC", "PS", "Xbox"]
  },
  {
    id: 12,
    title: "Red Dead Redemption 2",
    steamPrice: "₹3,999",
    epicPrice: "₹3,749",
    steamLink: "https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/",
    epicLink: "https://store.epicgames.com/en-US/p/red-dead-redemption-2",
    views: 8100,
    likes: 7700,
    reviews: ["Visually stunning.", "Epic story.", "Slow-paced but worth it."],
    type: "trending",
    genre: "Action",
    platform: ["PC", "PS", "Xbox"]
  },
  {
    id: 13,
    title: "PUBG: Battlegrounds",
    steamPrice: "Free",
    epicPrice: "Not Available",
    steamLink: "https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/",
    epicLink: null,
    views: 6500,
    likes: 6000,
    reviews: ["Tactical gameplay.", "High adrenaline.", "Frequent updates."],
    type: "trending",
    genre: "Battle Royale",
    platform: ["PC", "Mobile", "Xbox"]
  },
  {
    id: 14,
    title: "Stray",
    steamPrice: "₹2,499",
    epicPrice: "₹2,299",
    steamLink: "https://store.steampowered.com/app/1332010/Stray/",
    epicLink: "https://store.epicgames.com/en-US/p/stray",
    views: 3400,
    likes: 3100,
    reviews: ["Cute and emotional.", "Innovative perspective.", "Great soundtrack."],
    type: "basic",
    genre: "Adventure",
    platform: ["PC", "PS"]
  },
  {
    id: 15,
    title: "Hollow Knight",
    steamPrice: "₹499",
    epicPrice: "₹449",
    steamLink: "https://store.steampowered.com/app/367520/Hollow_Knight/",
    epicLink: "https://store.epicgames.com/en-US/p/hollow-knight",
    views: 3900,
    likes: 3700,
    reviews: ["Tight gameplay.", "Dark beautiful world.", "Superb boss fights."],
    type: "suggested",
    genre: "Metroidvania",
    platform: ["PC", "Switch"]
  },
    {
    id: 16,
    title: "Resident Evil 4 Remake",
    steamPrice: "₹3,599",
    epicPrice: "₹3,299",
    steamLink: "https://store.steampowered.com/app/2050650/Resident_Evil_4/",
    epicLink: "https://store.epicgames.com/en-US/p/resident-evil-4-remake",
    views: 4500,
    likes: 4300,
    reviews: ["Intense horror.", "Perfectly modernized.", "A classic reborn."],
    type: "trending",
    genre: "Horror",
    platform: ["PC", "PS", "Xbox"]
  },
  {
    id: 17,
    title: "It Takes Two",
    steamPrice: "₹1,499",
    epicPrice: "₹1,399",
    steamLink: "https://store.steampowered.com/app/1426210/It_Takes_Two/",
    epicLink: "https://store.epicgames.com/en-US/p/it-takes-two",
    views: 2800,
    likes: 2500,
    reviews: ["Great for co-op.", "Clever puzzles.", "Unique story."],
    type: "suggested",
    genre: "Puzzle",
    platform: ["PC", "PS", "Xbox"]
  },
  {
    id: 18,
    title: "God of War",
    steamPrice: "₹3,299",
    epicPrice: "₹3,099",
    steamLink: "https://store.steampowered.com/app/1593500/God_of_War/",
    epicLink: "https://store.epicgames.com/en-US/p/god-of-war",
    views: 8200,
    likes: 7800,
    reviews: ["Epic action.", "Great story.", "Smooth combat."],
    type: "trending",
    genre: "Action",
    platform: ["PC", "PS"]
  },
  {
    id: 19,
    title: "The Forest",
    steamPrice: "₹585",
    epicPrice: "₹549",
    steamLink: "https://store.steampowered.com/app/242760/The_Forest/",
    epicLink: "https://store.epicgames.com/en-US/p/the-forest",
    views: 2500,
    likes: 2200,
    reviews: ["Creepy and fun.", "Build and survive.", "Multiplayer is chaotic!"],
    type: "suggested",
    genre: "Survival",
    platform: ["PC", "PS"]
  },
  {
    id: 20,
    title: "The Sims 4",
    steamPrice: "Free",
    epicPrice: "Free",
    steamLink: "https://store.steampowered.com/app/1222670/The_Sims_4/",
    epicLink: "https://store.epicgames.com/en-US/p/the-sims-4",
    views: 4000,
    likes: 3800,
    reviews: ["Best life simulator.", "Lots of expansions.", "Custom content is fun."],
    type: "basic",
    genre: "Simulation",
    platform: ["PC"]
  },
    {
    id: 21,
    title: "Far Cry 6",
    steamPrice: "₹3,999",
    epicPrice: "₹3,799",
    steamLink: "https://store.steampowered.com/app/2369390/Far_Cry_6/",
    epicLink: "https://store.epicgames.com/en-US/p/far-cry-6",
    views: 3900,
    likes: 3700,
    reviews: ["Great action.", "Beautiful open world.", "Fun weapons."],
    type: "trending",
    genre: "Shooter",
    platform: ["PC", "PS", "Xbox"]
  },
  {
    id: 22,
    title: "Little Nightmares II",
    steamPrice: "₹1,199",
    epicPrice: "₹1,149",
    steamLink: "https://store.steampowered.com/app/860510/Little_Nightmares_II/",
    epicLink: "https://store.epicgames.com/en-US/p/little-nightmares-2",
    views: 2300,
    likes: 2100,
    reviews: ["Creepy but cute.", "Great puzzles.", "Visuals are stunning."],
    type: "suggested",
    genre: "Horror",
    platform: ["PC", "Switch"]
  },
  {
    id: 23,
    title: "Doom Eternal",
    steamPrice: "₹1,999",
    epicPrice: "₹1,899",
    steamLink: "https://store.steampowered.com/app/782330/DOOM_Eternal/",
    epicLink: "https://store.epicgames.com/en-US/p/doom-eternal",
    views: 4300,
    likes: 4100,
    reviews: ["Intense combat.", "Great soundtrack.", "Satisfying gunplay."],
    type: "basic",
    genre: "Shooter",
    platform: ["PC", "PS", "Xbox"]
  },
  {
    id: 24,
    title: "Fall Guys",
    steamPrice: "Not Available",
    epicPrice: "Free",
    steamLink: null,
    epicLink: "https://store.epicgames.com/en-US/p/fall-guys",
    views: 5800,
    likes: 5400,
    reviews: ["Fun with friends.", "Quick rounds.", "Hilarious chaos."],
    type: "suggested",
    genre: "Party",
    platform: ["PC", "PS", "Switch"]
  },
  {
    id: 25,
    title: "Battlefield 2042",
    steamPrice: "₹3,499",
    epicPrice: "₹3,299",
    steamLink: "https://store.steampowered.com/app/1517290/Battlefield_2042/",
    epicLink: "https://store.epicgames.com/en-US/p/battlefield-2042",
    views: 4600,
    likes: 4200,
    reviews: ["Massive battles.", "Nice graphics.", "Needs optimization."],
    type: "trending",
    genre: "Shooter",
    platform: ["PC", "PS", "Xbox"]
  },
  {
    id: 26,
    title: "Stardew Valley",
    steamPrice: "₹479",
    epicPrice: "₹449",
    steamLink: "https://store.steampowered.com/app/413150/Stardew_Valley/",
    epicLink: "https://store.epicgames.com/en-US/p/stardew-valley",
    views: 3700,
    likes: 3600,
    reviews: ["Peaceful and fun.", "Relaxing farming.", "Lots of content."],
    type: "basic",
    genre: "Simulation",
    platform: ["PC", "Mobile", "Switch"]
  },
  {
    id: 27,
    title: "Overwatch 2",
    steamPrice: "Free",
    epicPrice: "Not Available",
    steamLink: "https://store.steampowered.com/app/2357570/Overwatch_2/",
    epicLink: null,
    views: 5100,
    likes: 4800,
    reviews: ["Team-based FPS.", "Colorful and fast.", "Great heroes."],
    type: "suggested",
    genre: "Shooter",
    platform: ["PC", "PS", "Xbox"]
  },
  {
    id: 28,
    title: "Forza Horizon 5",
    steamPrice: "₹4,299",
    epicPrice: "₹4,099",
    steamLink: "https://store.steampowered.com/app/1551360/Forza_Horizon_5/",
    epicLink: "https://store.epicgames.com/en-US/p/forza-horizon-5",
    views: 6000,
    likes: 5700,
    reviews: ["Beautiful cars.", "Massive world.", "Fun races."],
    type: "trending",
    genre: "Racing",
    platform: ["PC", "Xbox"]
  },
  {
    id: 29,
    title: "Death Stranding",
    steamPrice: "₹2,999",
    epicPrice: "₹2,799",
    steamLink: "https://store.steampowered.com/app/1190460/DEATH_STRANDING/",
    epicLink: "https://store.epicgames.com/en-US/p/death-stranding",
    views: 3200,
    likes: 3100,
    reviews: ["Unique gameplay.", "Great visuals.", "Strange but cool."],
    type: "basic",
    genre: "Adventure",
    platform: ["PC", "PS"]
  },
  {
    id: 30,
    title: "Left 4 Dead 2",
    steamPrice: "₹299",
    epicPrice: "Not Available",
    steamLink: "https://store.steampowered.com/app/550/Left_4_Dead_2/",
    epicLink: null,
    views: 4900,
    likes: 4700,
    reviews: ["Classic zombie shooter.", "Great co-op.", "Still fun today."],
    type: "suggested",
    genre: "Shooter",
    platform: ["PC"]
  }
];

